service: polyfill

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'us-west-2'}

package:
  exclude:
  - server.js
  - coverage/
  - test/

functions:
  polyfill:
    handler: handler.handle
    events:
    - http:
        path: polyfill/v3
        method: get
        cors: true
