service: polyfill

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-west-2

package:
  exclude:
  - server.js
  - test/

functions:
  polyfill:
    handler: handler.handle
    events:
    - http:
        path: polyfill/v2
        method: get
        cors: true
